// <auto-generated />
using System;
using J_A_Jewelry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace J_A_Jewelry.Migrations
{
    [DbContext(typeof(IsetechcJewelryInventoryContext))]
    [Migration("20260405232440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("J_A_Jewelry.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoryNumber");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraInformation")
                        .HasColumnType("text")
                        .HasColumnName("extraInformation");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("postalCode");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.CustomerPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int(11)")
                        .HasColumnName("customerId");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("paymentDate");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int(11)")
                        .HasColumnName("paymentMethodId");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("salesOrderId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "customerId");

                    b.HasIndex(new[] { "PaymentMethodId" }, "paymentMethodId");

                    b.HasIndex(new[] { "SalesOrderId" }, "salesOrderId");

                    b.ToTable("CustomerPayments");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("warehouseId");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "productId");

                    b.HasIndex(new[] { "WarehouseId" }, "warehouseId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("J_A_Jewelry.Models.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("ManualEntryReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("manualEntryReason");

                    b.Property<DateTime?>("MovementDate")
                        .HasColumnType("datetime")
                        .HasColumnName("movementDate");

                    b.Property<string>("MovementType")
                        .HasColumnType("enum('IN','OUT')")
                        .HasColumnName("movementType");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("purchaseOrderId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int(11)")
                        .HasColumnName("quantity");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("salesOrderId");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("warehouseId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "productId")
                        .HasDatabaseName("productId1");

                    b.HasIndex(new[] { "PurchaseOrderId" }, "purchaseOrderId");

                    b.HasIndex(new[] { "SalesOrderId" }, "salesOrderId")
                        .HasDatabaseName("salesOrderId1");

                    b.HasIndex(new[] { "WarehouseId" }, "warehouseId")
                        .HasDatabaseName("warehouseId1");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PriceListDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("PriceListId")
                        .HasColumnType("int(11)")
                        .HasColumnName("priceListId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("validFrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("validTo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PriceListId" }, "priceListId");

                    b.HasIndex(new[] { "ProductId" }, "productId")
                        .HasDatabaseName("productId2");

                    b.ToTable("PriceListDetails");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int(11)")
                        .HasColumnName("categoryId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "categoryId");

                    b.HasIndex(new[] { "ProductId" }, "productId")
                        .HasDatabaseName("productId3");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imageUrl");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "productId")
                        .HasDatabaseName("productId4");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("purchaseOrderId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int(11)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unitPrice");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "productId")
                        .HasDatabaseName("productId5");

                    b.HasIndex(new[] { "PurchaseOrderId" }, "purchaseOrderId")
                        .HasDatabaseName("purchaseOrderId1");

                    b.ToTable("PurchaseOrderDetail", (string)null);
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PurchaseOrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("orderDate");

                    b.Property<DateTime?>("ReceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("receptionDate");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int(11)")
                        .HasColumnName("supplierId");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SupplierId" }, "supplierId");

                    b.ToTable("PurchaseOrderHeader", (string)null);
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SalesOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int(11)")
                        .HasColumnName("quantity");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("salesOrderId");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unitPrice");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "productId")
                        .HasDatabaseName("productId6");

                    b.HasIndex(new[] { "SalesOrderId" }, "salesOrderId")
                        .HasDatabaseName("salesOrderId2");

                    b.ToTable("SalesOrderDetail", (string)null);
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SalesOrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int(11)")
                        .HasColumnName("customerId");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int(11)")
                        .HasColumnName("paymentMethodId");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("date")
                        .HasColumnName("saleDate");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "customerId")
                        .HasDatabaseName("customerId1");

                    b.HasIndex(new[] { "PaymentMethodId" }, "paymentMethodId")
                        .HasDatabaseName("paymentMethodId1");

                    b.ToTable("SalesOrderHeader", (string)null);
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SalesTaxDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("salesOrderId");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("taxAmount");

                    b.Property<string>("TaxType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("taxType");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SalesOrderId" }, "salesOrderId")
                        .HasDatabaseName("salesOrderId3");

                    b.ToTable("SalesTaxDetail", (string)null);
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("ClientNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("clientNumber");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("ShipVia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("shipVia");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SupplierProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("ArtCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("artCode");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.Property<string>("StyleCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("styleCode");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int(11)")
                        .HasColumnName("supplierId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "productId")
                        .HasDatabaseName("productId7");

                    b.HasIndex(new[] { "SupplierId" }, "supplierId")
                        .HasDatabaseName("supplierId1");

                    b.ToTable("SupplierProducts");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.CustomerPayment", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Customer", "Customer")
                        .WithMany("CustomerPayments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("CustomerPayments_ibfk_1");

                    b.HasOne("J_A_Jewelry.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("CustomerPayments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("CustomerPayments_ibfk_3");

                    b.HasOne("J_A_Jewelry.Models.SalesOrderHeader", "SalesOrder")
                        .WithMany("CustomerPayments")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("CustomerPayments_ibfk_2");

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Inventory", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Inventory_ibfk_2");

                    b.HasOne("J_A_Jewelry.Models.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Inventory_ibfk_1");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.InventoryMovement", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("InventoryMovements_ibfk_1");

                    b.HasOne("J_A_Jewelry.Models.PurchaseOrderHeader", "PurchaseOrder")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("InventoryMovements_ibfk_3");

                    b.HasOne("J_A_Jewelry.Models.SalesOrderHeader", "SalesOrder")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("InventoryMovements_ibfk_4");

                    b.HasOne("J_A_Jewelry.Models.Warehouse", "Warehouse")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("InventoryMovements_ibfk_2");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("SalesOrder");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PriceListDetail", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.PriceList", "PriceList")
                        .WithMany("PriceListDetails")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("PriceListDetails_ibfk_1");

                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("PriceListDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("PriceListDetails_ibfk_2");

                    b.Navigation("PriceList");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.ProductCategory", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("ProductCategories_ibfk_1");

                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("ProductCategories_ibfk_2");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.ProductImage", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("ProductImages_ibfk_1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("PurchaseOrderDetail_ibfk_2");

                    b.HasOne("J_A_Jewelry.Models.PurchaseOrderHeader", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("PurchaseOrderDetail_ibfk_1");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PurchaseOrderHeader", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrderHeaders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("PurchaseOrderHeader_ibfk_1");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SalesOrderDetail", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("SalesOrderDetail_ibfk_2");

                    b.HasOne("J_A_Jewelry.Models.SalesOrderHeader", "SalesOrder")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("SalesOrderDetail_ibfk_1");

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SalesOrderHeader", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Customer", "Customer")
                        .WithMany("SalesOrderHeaders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("SalesOrderHeader_ibfk_1");

                    b.HasOne("J_A_Jewelry.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("SalesOrderHeaders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("SalesOrderHeader_ibfk_2");

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SalesTaxDetail", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.SalesOrderHeader", "SalesOrder")
                        .WithMany("SalesTaxDetails")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("SalesTaxDetail_ibfk_1");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SupplierProduct", b =>
                {
                    b.HasOne("J_A_Jewelry.Models.Product", "Product")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("SupplierProducts_ibfk_2");

                    b.HasOne("J_A_Jewelry.Models.Supplier", "Supplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("SupplierProducts_ibfk_1");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Customer", b =>
                {
                    b.Navigation("CustomerPayments");

                    b.Navigation("SalesOrderHeaders");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PaymentMethod", b =>
                {
                    b.Navigation("CustomerPayments");

                    b.Navigation("SalesOrderHeaders");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PriceList", b =>
                {
                    b.Navigation("PriceListDetails");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryMovements");

                    b.Navigation("PriceListDetails");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");

                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("SalesOrderDetails");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.PurchaseOrderHeader", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.SalesOrderHeader", b =>
                {
                    b.Navigation("CustomerPayments");

                    b.Navigation("InventoryMovements");

                    b.Navigation("SalesOrderDetails");

                    b.Navigation("SalesTaxDetails");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrderHeaders");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("J_A_Jewelry.Models.Warehouse", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
